### ISSUE TITLE
click the save button and then the cilpper just keep on saving……

### ISSUE THREAD

**Issue by kohakunomiyuka** [yutakobayashidev/dlsite-notion-clipper#1]
I followed the steps one by one and loaded the extention successfully, but when I browsered the product's page,turned on the extention and then clicked the save button, I saw the button turned to "saving" and nothing happen. I checked my api and id key and I thought they were correct. I don't know why the extension did't work……orz

![image](https://github.com/yutakobayashidev/dlsite-notion-clipper/assets/79520731/778ba404-f574-4238-8c66-3b97a6c5d599)

**Comment by yutakobayashidev** [comment]
HI @1509438955!  I apologize for the delay. I was unable to reproduce this issue. Upon successful saving, you will be redirected to the created Notion page.

Please review the extension permissions, the Notion API key, Notion's database structure, and the access permissions to the pages. Additionally, I recommend debugging in development mode.

If time allows, I plan to add more detailed error handling code.

**Comment by kohakunomiyuka** [comment]
Thank you for your reply.I found the problem was that i renamed the .env file so the extension couldn't work.So it was my fault(orz
